from patch import (
    patch_engine,
    diff_generator,
    validator,
)

from patch.models import (
    FileEdit,
    EditType,
)


edit = FileEdit(
    file="README.md",
    edit_type=EditType.APPEND,
    target="",
    replacement="\nGenerated by DeepJarvis\n",
    reason="Demo",
)

old, new = patch_engine.apply(edit)

ok, message = validator.validate_python(
    new
) if edit.file.endswith(".py") else (True, "")

print()

print("Valid:", ok)

print()

print(diff_generator.generate(
    old,
    new,
    edit.file,
))